### ISSUE TITLE
Blank page on submitting blog posts

### ISSUE THREAD

**Issue by razvand** [unikraft/docs#164]
The [blog](https://unikraft.org/blog/) features [a link on submitting a blog post](https://unikraft.org/docs/contributing/blog-case-studies/) that's pointing to a [blank page](https://github.com/unikraft/docs/blob/main/content/en/docs/contributing/blog-case-studies.md). This page needs to be filled.

**Comment by StefanJum** [comment]
Solved by website redesign.
