### ISSUE TITLE
Add information on running `markdownlint` locally

### ISSUE THREAD

**Issue by razvand** [unikraft/docs#165]
The repository features [`super-linter`](https://github.com/github/super-linter) as a worfklow in the [`.github/workflow/` directory](https://github.com/unikraft/docs/tree/main/.github/workflows). This is enabled at each push and it runs [`markdownlint-cli`](https://github.com/igorshubovych/markdownlint-cli).

We need to update the [`README.md` file](https://github.com/unikraft/docs/blob/main/README.md) and [documentation on submitting a blog post](https://github.com/unikraft/docs/blob/main/content/en/docs/contributing/submitting-changes.md) with information on installing and using `markdown-cli` locally, before creating a PR.

Installing is done using:

```console
$ npm install -g markdownlint-cli
```

Checking a Markdown file is done using a command such as the one below. The command below is run while inside the `content/en/blog/` directory:

```console
$ markdownlint --config ../../../.github/workflows/config/config.json --rules ../../../.github/workflows/rules/rules.js *.md
```

**Comment by StefanJum** [comment]
Closed by #171.
