### ISSUE TITLE
Disable `MD101/backtick-keywords` in Hugo shortcode

### ISSUE THREAD

**Issue by razvand** [unikraft/docs#169]
When using [Hugo shortcodes](https://gohugo.io/content-management/shortcodes/), the [`MD101` rule](https://github.com/unikraft/docs/blob/main/.github/workflows/rules/md101.js), for using backticks, should be disabled.

For example, for this shortcode:

```none
{{< figure
    src="/assets/imgs/morello-unikraft-build-option.png"
    title="The new Morello option which can be enabled in the Unikraft platform configuration menu"
    position="center"
>}}
```

the following warning is shown:

```
MD101/backtick-keywords Keywords must be fenced and must be in appropriate case. [Expected `.png`. Actual .png.]
```

**Comment by StefanJum** [comment]
covered by the website refactoring
