### ISSUE TITLE
Add documentation for running the checkpatch

### ISSUE THREAD

**Issue by RaduNichita** [unikraft/docs#180]
When contributing to most of the Unikraft's repositories, there is a requirement to run the checkpatch before submitting the PRs. Moreover, a Github action is run in this scenario in order to detect potential coding style issues. 

However, there is not specified in the documentation how to run the checkpatch script locally.

**Comment by StefanJum** [comment]
The checkpatch usage is documented [here](https://unikraft.org/docs/contributing/testing/#using-checkpatchpl). We could add a little more content to it indeed.
