### ISSUE TITLE
`community/hackathons`: Use `lib-musl` instead of `lib-newlib`

### ISSUE THREAD

**Issue by razvand** [unikraft/docs#201]
[Hackathon sessions](https://unikraft.org/community/hackathons/sessions/) use [`lib-newlib`](https://github.com/unikraft/lib-newlib) as the default libc. `lib-newlib` is no longer support and must be replaced with [`lib-musl`](https://github.com/unikraft/lib-musl).

**Comment by sameerp815** [comment]
Could I have this issue?

**Comment by StefanJum** [comment]
covered by the website refactoring
