### ISSUE TITLE
`community/hackatons`: Use official `app-elfloader` release

### ISSUE THREAD

**Issue by razvand** [unikraft/docs#202]
The [`Binary Compatibility` section](https://unikraft.org/community/hackathons/sessions/bincompat/) of the hackathons use an old version of the `app-elfloader`, before [its official release](https://github.com/unikraft/app-elfloader). The [`app-elfloader` official release](https://github.com/unikraft/app-elfloader) should be used throughout the session.

**Comment by afzal442** [comment]
Hey @razvand ! I don't find in the docs where you point out. Thanks

> old version of the app-elfloader

**Comment by StefanJum** [comment]
covered by the website refactoring
