### ISSUE TITLE
Dead Links all Around

### ISSUE THREAD

**Issue by craciunoiuc** [unikraft/docs#23]
There are a lot of dead links on the page. Someone should do a pass through everything and connect components.

Some examples:

![image](https://user-images.githubusercontent.com/46280801/152634052-942b29cc-5068-4bfd-99a5-9fd27b523995.png)

![image](https://user-images.githubusercontent.com/46280801/152634064-aaf04252-df03-4af1-9328-42a6e98f5726.png)

**Comment by razvand** [comment]
I fixed a bunch of those. @gabrielmocanu is there anything missing?

**Comment by gabrielmocanu** [comment]
@razvand  I made a PR with other broken links.

Can you have a look at it? #39 

After this, we can close this issue.
