### ISSUE TITLE
Documentation on syscalls was dropped

### ISSUE THREAD

**Issue by Mic92** [unikraft/docs#317]
In https://github.com/unikraft/docs/commit/6d20fc516422ac859329f6d3fc5af696155a2b63 most of the  documentation of the project was dropped. I was planning on a university course that would include students defining their own system call (UK_SYSCALL_R_DEFINE) for next year and writing a custom allocator. Are you planning on restoring this documentation? Otherwise I need to consider a different operating system for the course.

**Comment by StefanJum** [comment]
On Sat, Sep 16, 2023 at 10:08:48PM -0700, Jörg Thalheim wrote:
> In https://github.com/unikraft/docs/commit/6d20fc516422ac859329f6d3fc5af696155a2b63 most of the  documentation of the project was dropped. I was planning on a university course that would include students defining their own system call (UK_SYSCALL_R_DEFINE) for next year. Are you planning on restoring this documentation? Otherwise I need to consider a different operating system for the course.

Hi. Yes, we are slowly restoring the documentation that got deleted,
hopefully everything will be up soon.

**Comment by Mic92** [comment]
Thanks!

**Comment by StefanJum** [comment]
The docs are back up @Mic92 https://unikraft.org/docs/internals/syscall-shim

**Comment by Mic92** [comment]
Thanks a lot!
