### ISSUE TITLE
Fix SVG figure fonts

### ISSUE THREAD

**Issue by nderjung** [unikraft/docs#33]
Some figures based on SVGs have an embedded font selection for the site (the default `Inter`) but this does not necessarily show for every browser.

This issue is used to track updating the `font-family` of related SVGs with a more compatible font family matrix.

**Comment by gabrielmocanu** [comment]
Hi @nderjung,

Do you think `Arial` would be a more compatible font family than `Inter`?

**Comment by gabrielmocanu** [comment]
I made a PR for this (#40), but I am not sure if this is the only thing that it should be done.
