### ISSUE TITLE
Strace Tool

### ISSUE THREAD

**Issue by iampk14** [unikraft/docs#410]
I am currently working on a C++ program named helloworld.cpp, and I have integrated strace to trace system calls during execution. The program compiles and runs without any errors, indicating a successful build. However, despite the successful execution, I'm not receiving any output from strace.

I have verified that the program is functioning correctly by executing it without strace and observing the expected output. The issue seems to be specifically related to the strace command not providing any output or trace information.

I would appreciate any insights or suggestions on how to troubleshoot this issue and ensure that strace properly traces system calls in my helloworld.cpp program.

**Comment by StefanJum** [comment]
Hi @iampk14. We should probably move this discussion to the [Discord server](https://discord.com/invite/RG5ZQGKxyW), since this is only the documentation website repo. Please post the question on the discord `#forum` channel, and we can get into more details there.
